### ISSUE TITLE
Connect to prometheus

### ISSUE THREAD

**Issue by daviddanko** [modem7/hddtemp-docker#18]
Hi, 

is there a way to send these data to prometheus? I'd like to show the temperatures in grafana. I can't find anything about this.

Thanks.

**Comment by modem7** [comment]
Heya,

I'm currently using telegraf to grab the data from the container currently, then telegraf sends it to Grafana.

**Comment by daviddanko** [comment]
Thanks. I am halfway there I think. Would you mind showing me the influx query of the panel? I'm afraid I'm missing something in there.

**Comment by modem7** [comment]
Sure thing!

For the left panel
![image](https://user-images.githubusercontent.com/4349962/187774869-30c3a0de-057c-4f30-a8c2-c36500e66ae3.png)

For the right panel
![image](https://user-images.githubusercontent.com/4349962/187774959-1108d6e2-b0b0-4d02-bee5-218ee6b5329f.png)

**Comment by daviddanko** [comment]
Thanks!
