### ISSUE TITLE
Wrong Arch for linux/arm64 in dockerhub

### ISSUE THREAD

**Issue by sjafferali** [modem7/hddtemp-docker#19]
I am using `modem7/hddtemp-docker:latest` from dockerhub on my arm64 machine and receiving the below error. 

```
2023-01-17T14:03:48.562005713Z /bin/sh: 1: hddtemp: Exec format error
2023-01-17T14:03:55.684704995Z /bin/sh: 1: hddtemp: Exec format error
```

Is it possible the images are incorrectly tagged arm64? It seems like this has occurred before in https://github.com/modem7/hddtemp-docker/issues/6 .

**Comment by modem7** [comment]
Looks like the binary isn't right for ARM. 

I'll have to rethink about how I build this, chances are, I'll have to build from scratch for each version.

**Comment by modem7** [comment]
@sjafferali Could you try the latest version for me please?

**Comment by sjafferali** [comment]
@modem7, just tested, the new version works without errors. Thank you!

As an aside, it would be really great if this repo had a versioning system that would allow me to lock my compose file to this version, rather than using the `latest` tag. 

Thanks for the prompt response!

**Comment by modem7** [comment]
> @modem7, just tested, the new version works without errors. Thank you!
> 
> As an aside, it would be really great if this repo had a versioning system that would allow me to lock my compose file to this version, rather than using the `latest` tag.
> 
> Thanks for the prompt response!

Agreed to a degree - normally I do versioning depending on the package version itself. 

Unfortunately hddtemp hasn't really been updated for about 12 years! I'm currently using the version from https://github.com/vitlav/hddtemp - but looking now, it looks like they have tags, so I'll get it tagged against theirs now!

**Comment by modem7** [comment]
All tagged for you. 

Latest version is [0.4.3.1](https://hub.docker.com/repository/docker/modem7/hddtemp-docker/general)

0.4.3 is what https://github.com/vitlav/hddtemp is on, and I've added the .1 for changes I'll make. 

Hope that's alright!

**Comment by sjafferali** [comment]
This is perfect. Thank you @modem7 !
