### ISSUE TITLE
0.4.3.2 docker image fails to launch due to missing GLIBC dependency

### ISSUE THREAD

**Issue by Skrallexxx** [modem7/hddtemp-docker#23]
Hello,

Latest docker image / tag is failing to launch for me with the below error.

`
hddtemp: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by hddtemp)
`

Reverting to 0.4.3.1 works as expected.

**Comment by modem7** [comment]
Looks like there's an issue with hddtemp in Debian Bookworm.

I'm making a new build now to see if this mitigates the issue.

**Comment by modem7** [comment]
@Skrallexxx Could you give it a test please?

**Comment by Skrallexxx** [comment]
I had to force an update to the image since your new version has the same tag, but it appears to work now. Thanks for following it up!
