### ISSUE TITLE
Wrong arch pushed to dockerhub?

### ISSUE THREAD

**Issue by razaqq** [modem7/hddtemp-docker#6]
When running the image with `image: modem7/hddtemp-docker:latest` i get:

`hddtemp   | standard_init_linux.go:228: exec user process caused: exec format error`

Im on arm64, so this has to have pulled the amd64 image. You sure you didnt incorretly tag the images for the wrong arch?

**Comment by modem7** [comment]
I'll have a look and reupload if needs be!

I'll respond when I figure it out

**Comment by razaqq** [comment]
When building the image locally it works just fine, so this has to be a deployment issue.

**Comment by modem7** [comment]
Give it a try now, just finished rebuilding and redeploying.

All the arches are in the same manifest, so it should pull the appropriate version for you automatically.

**Comment by modem7** [comment]
> yeah that fixed it thanks
> 
> one more remark while we are at it, you should consider using alpine as a base image, you could get this image from 100MB down to like 10MB most likely just an idea

I wish!

Unfortunately, HDDTemp is so outdated that Alpine won't put it on their repos.

https://gitlab.alpinelinux.org/alpine/aports/-/issues/7296

**Comment by modem7** [comment]
@razaqq 

Just an FYI, I've finished rebuilding hddtemp from source from https://github.com/vitlav/hddtemp. 

I've also tweaked a few things, and the image size is now ~30mb. 

Hope that helps!
